#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’
use_frameworks!

def pods
    pod 'AFNetworking', '2.6.3'
    pod 'Reachability', '~> 3.2'
    pod 'SVProgressHUD'
    pod 'PureLayout', '~> 3.0.1'
    pod 'FMDB'
    pod 'MJExtension'
    pod "LLModularization", :path => "../"
end

target 'LLModularizationDemo' do
	pods
end
